language: php
php:
  # - 5.6
  # - 7.0
  - 7.2

services:
  - mysql
  - mongodb

addons:
  apt:
    packages:
    - ldap-utils
    - slapd

before_install:
  # - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - mysql -e 'create database auth;'
  - mysql -e 'create database p_auth;'

install:
  - composer require php-coveralls/php-coveralls
  - nvm install stable

before_script:
  - mkdir -p build/logs
  - mkdir /tmp/slapd
  - slapd -f tests/travis/LDAP/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/travis/LDAP/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/travis/LDAP/user.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/travis/LDAP/INITIAL_TESTDATA.ldif

script:
  - vendor/bin/phpunit -c phpunit_travis.xml --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/php-coveralls -v; fi;'
